# IDSphere database settings
spring.datasource.url=jdbc:postgresql://idsphere.db:5432/idsphere
spring.datasource.username=idsphere
spring.datasource.password=${IDS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# DB pool configuration
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=20

# tables creation
spring.jpa.hibernate.ddl-auto=update
# schema creation
spring.jpa.generate-ddl=true

# The session needs to be shared across all the request handling
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

# fetch lazy loaded relations/associations
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY

spring.jpa.properties.hibernate.jdbc.fetch_size=30
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.cache.jcache.config=classpath:ehcache.xml

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# swagger properties
springdoc.paths-to-match=/services/rest/**
# swagger-ui properties
springdoc.swagger-ui.deepLinking=true
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.showCommonExtensions=true
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.validatorUrl=none
springdoc.swagger-ui.filter=true

#JMX endpoint
spring.jmx.default-domain=${spring.application.name:ids}

#actuator management
management.endpoint.health.show-components=WHEN_AUTHORIZED
management.endpoint.health.show-details=WHEN_AUTHORIZED
management.endpoint.health.roles=ADMIN,ACTUATOR

# IDS-Workflow-client settings
ids.workflow.client.url=http://localhost:8080/IDSWorkflow/
ids.workflow.jwt.passphrase=04be8eecd00bf213958eb9386f852c73064b036870075f9096acfe7d47b8c1e6
ids.workflow.jwt.claims-field=jti

ids.provisioning.bundle-folder=work/bundles/

ids.web.header.client-ip.keep-only-first=true

# only usable if Sng is not configured with IDS (IDS is installed as a standalone app)
#ids.web.security.session.key=PRIVATE_KEY_TO_CHANGE
#ids.web.security.session.validity-seconds=43200
#ids.web.security.users[0].username=admin
#ids.web.security.users[0].password=$IDS_ADMIN_PASSWORD$
#ids.web.security.users[0].roles=ADMIN,ACTUATOR

ids.web.security.http-basic.enabled=true

ids.notifier.email.from-default=no-reply@ilex-international.com
ids.smtp.host-default=localhost
ids.smtp.port-default=25

# Désactive le tracking de session via URL (utilise uniquement le cookie)
server.servlet.session.tracking-modes=COOKIE
